<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>annotations</Nullable>
    <Version>0.1.2</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Utils\GCatcode.Utils.csproj" />
  </ItemGroup>

</Project>
