// <auto-generated />
using System;
using GCatcode.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GCatcode.DataBase.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260209022352_BaseMigration")]
    partial class BaseMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GCatcode.DataBase.Models.CL_Controller", b =>
                {
                    b.Property<int>("ControllerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ControllerId"));

                    b.Property<bool>("Available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ControllerPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ControllerId");

                    b.ToTable("CL_Controllers", (string)null);

                    b.HasData(
                        new
                        {
                            ControllerId = 1,
                            Available = true,
                            ControllerPath = "admin/users",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Controller for users management",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "UsersController"
                        },
                        new
                        {
                            ControllerId = 2,
                            Available = true,
                            ControllerPath = "admin/roles",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Controller for roles management",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "RolesController"
                        },
                        new
                        {
                            ControllerId = 3,
                            Available = true,
                            ControllerPath = "admin/permissions",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Controller for permissions management",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "PermissionsController"
                        });
                });

            modelBuilder.Entity("GCatcode.DataBase.Models.CL_ControllerMethod", b =>
                {
                    b.Property<int>("MethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MethodId"));

                    b.Property<bool>("Available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ControllerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PermissionType")
                        .HasColumnType("int");

                    b.HasKey("MethodId");

                    b.HasIndex("ControllerId", "Name")
                        .IsUnique();

                    b.ToTable("CL_ControllerMethods", (string)null);

                    b.HasData(
                        new
                        {
                            MethodId = 1,
                            Available = true,
                            ControllerId = 1,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Listar usuarios",
                            Endpoint = "/admin/Users",
                            HttpMethod = "GET",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "GetAll",
                            PermissionType = 1
                        },
                        new
                        {
                            MethodId = 2,
                            Available = true,
                            ControllerId = 1,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Obtener usuario por ID",
                            Endpoint = "/admin/Users/{id}",
                            HttpMethod = "GET",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "GetById",
                            PermissionType = 1
                        },
                        new
                        {
                            MethodId = 3,
                            Available = true,
                            ControllerId = 1,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Crear usuario",
                            Endpoint = "/admin/Users",
                            HttpMethod = "POST",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Create",
                            PermissionType = 2
                        },
                        new
                        {
                            MethodId = 4,
                            Available = true,
                            ControllerId = 1,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Actualizar usuario",
                            Endpoint = "/admin/Users/{id}",
                            HttpMethod = "PUT",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Update",
                            PermissionType = 2
                        },
                        new
                        {
                            MethodId = 5,
                            Available = true,
                            ControllerId = 1,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Eliminar usuario",
                            Endpoint = "/admin/Users/{id}",
                            HttpMethod = "DELETE",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Delete",
                            PermissionType = 3
                        },
                        new
                        {
                            MethodId = 6,
                            Available = true,
                            ControllerId = 2,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Listar roles",
                            Endpoint = "/admin/Roles",
                            HttpMethod = "GET",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "GetAll",
                            PermissionType = 1
                        },
                        new
                        {
                            MethodId = 7,
                            Available = true,
                            ControllerId = 2,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Obtener rol por ID",
                            Endpoint = "/admin/Roles/{id}",
                            HttpMethod = "GET",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "GetById",
                            PermissionType = 1
                        },
                        new
                        {
                            MethodId = 8,
                            Available = true,
                            ControllerId = 2,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Crear rol",
                            Endpoint = "/admin/Roles",
                            HttpMethod = "POST",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Create",
                            PermissionType = 2
                        },
                        new
                        {
                            MethodId = 9,
                            Available = true,
                            ControllerId = 2,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Actualizar rol",
                            Endpoint = "/admin/Roles/{id}",
                            HttpMethod = "PUT",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Update",
                            PermissionType = 2
                        },
                        new
                        {
                            MethodId = 10,
                            Available = true,
                            ControllerId = 2,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Eliminar rol",
                            Endpoint = "/admin/Roles/{id}",
                            HttpMethod = "DELETE",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Delete",
                            PermissionType = 3
                        });
                });

            modelBuilder.Entity("GCatcode.DataBase.Models.CL_Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<bool>("Available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("RolId");

                    b.ToTable("CL_Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            Available = true,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "All Access Development",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Dev"
                        },
                        new
                        {
                            RolId = 2,
                            Available = true,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Limited Access",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Guest"
                        },
                        new
                        {
                            RolId = 3,
                            Available = true,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Access parcial",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "User"
                        },
                        new
                        {
                            RolId = 4,
                            Available = true,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "All Access Administration",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("GCatcode.DataBase.Models.CL_View", b =>
                {
                    b.Property<int>("ViewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViewId"));

                    b.Property<bool>("Available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentViewId")
                        .HasColumnType("int");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ViewId");

                    b.ToTable("CL_Views", (string)null);

                    b.HasData(
                        new
                        {
                            ViewId = 1,
                            Available = true,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "DashboardIcon",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Dashboard",
                            Order = 1,
                            Route = "/dashboard"
                        },
                        new
                        {
                            ViewId = 2,
                            Available = true,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View for Adim tools",
                            Icon = "admin",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Admin",
                            Order = 0,
                            Route = "admin"
                        },
                        new
                        {
                            ViewId = 3,
                            Available = true,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View for users management",
                            Icon = "user",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Users",
                            Order = 0,
                            ParentViewId = 1,
                            Route = "admin/users"
                        },
                        new
                        {
                            ViewId = 4,
                            Available = true,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View for roles management",
                            Icon = "list",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Roles",
                            Order = 0,
                            ParentViewId = 1,
                            Route = "admin/roles"
                        },
                        new
                        {
                            ViewId = 5,
                            Available = true,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View for permisos management",
                            Icon = "auth",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Permisos",
                            Order = 0,
                            ParentViewId = 1,
                            Route = "admin/permisos"
                        });
                });

            modelBuilder.Entity("GCatcode.DataBase.Models.RL_UserRol", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("RL_UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RolId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RolId = 2
                        },
                        new
                        {
                            UserId = 1,
                            RolId = 3
                        },
                        new
                        {
                            UserId = 1,
                            RolId = 4
                        },
                        new
                        {
                            UserId = 2,
                            RolId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RolId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RolId = 4
                        });
                });

            modelBuilder.Entity("GCatcode.DataBase.Models.RL_ViewController", b =>
                {
                    b.Property<int>("ViewId")
                        .HasColumnType("int");

                    b.Property<int>("ControllerId")
                        .HasColumnType("int");

                    b.HasKey("ViewId", "ControllerId");

                    b.HasIndex("ControllerId");

                    b.ToTable("RL_ViewControllers", (string)null);

                    b.HasData(
                        new
                        {
                            ViewId = 3,
                            ControllerId = 1
                        },
                        new
                        {
                            ViewId = 4,
                            ControllerId = 2
                        },
                        new
                        {
                            ViewId = 5,
                            ControllerId = 3
                        });
                });

            modelBuilder.Entity("GCatcode.DataBase.Models.RL_ViewRol", b =>
                {
                    b.Property<int>("ViewId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("ViewId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("RL_ViewRoles", (string)null);

                    b.HasData(
                        new
                        {
                            ViewId = 1,
                            RolId = 1
                        },
                        new
                        {
                            ViewId = 3,
                            RolId = 1
                        },
                        new
                        {
                            ViewId = 4,
                            RolId = 1
                        },
                        new
                        {
                            ViewId = 5,
                            RolId = 1
                        },
                        new
                        {
                            ViewId = 1,
                            RolId = 4
                        },
                        new
                        {
                            ViewId = 3,
                            RolId = 4
                        },
                        new
                        {
                            ViewId = 4,
                            RolId = 4
                        },
                        new
                        {
                            ViewId = 5,
                            RolId = 4
                        },
                        new
                        {
                            ViewId = 1,
                            RolId = 3
                        },
                        new
                        {
                            ViewId = 1,
                            RolId = 2
                        });
                });

            modelBuilder.Entity("GCatcode.DataBase.Models.TR_RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_Token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId");

                    b.HasIndex("ExpiryDate", "IsRevoked")
                        .HasDatabaseName("IX_RefreshTokens_ExpiryDate_IsRevoked");

                    b.ToTable("TR_RefreshTokens", (string)null);
                });

            modelBuilder.Entity("GCatcode.DataBase.Models.TR_User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("Available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("TR_Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Available = true,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dev@local.com",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "bDN+lqTwOni3VvDVCpMZ/fdIOeLJWI4xr/pBMFxpmXrM2eKXisTjyE3Jl22qlVez",
                            UserName = "Dev"
                        },
                        new
                        {
                            UserId = 2,
                            Available = true,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "guest@local.com",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "ovs8iCBxayixik0xCdcm9juL4VTn7mJeScrfiWEyZdXRZi9N7pWb5qZoY4Ry+dpL",
                            UserName = "Guest"
                        },
                        new
                        {
                            UserId = 3,
                            Available = true,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user@local.com",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "LVrRLFuwP0EOJ9QAkhoWJFx8tab4KxUrGo1ME8wZRWHvM2saRRM3yAl1wLdBkPsu",
                            UserName = "User"
                        },
                        new
                        {
                            UserId = 4,
                            Available = true,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@local.com",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "pUoDuxUl0hWFYdvT+8Jg7TbBM6e634yhjrLE19bOTdODOpLoU8a3RRJIvhs2zAmf",
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("GCatcode.DataBase.Models.RL_UserRol", b =>
                {
                    b.HasOne("GCatcode.DataBase.Models.CL_Rol", "Rol")
                        .WithMany("UserRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GCatcode.DataBase.Models.TR_User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GCatcode.DataBase.Models.RL_ViewController", b =>
                {
                    b.HasOne("GCatcode.DataBase.Models.CL_Controller", "Controller")
                        .WithMany("ViewControllers")
                        .HasForeignKey("ControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GCatcode.DataBase.Models.CL_View", "View")
                        .WithMany("ViewControllers")
                        .HasForeignKey("ViewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Controller");

                    b.Navigation("View");
                });

            modelBuilder.Entity("GCatcode.DataBase.Models.RL_ViewRol", b =>
                {
                    b.HasOne("GCatcode.DataBase.Models.CL_Rol", "Rol")
                        .WithMany("ViewRols")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GCatcode.DataBase.Models.CL_View", "View")
                        .WithMany("ViewRols")
                        .HasForeignKey("ViewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("View");
                });

            modelBuilder.Entity("GCatcode.DataBase.Models.TR_RefreshToken", b =>
                {
                    b.HasOne("GCatcode.DataBase.Models.TR_User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GCatcode.DataBase.Models.CL_Controller", b =>
                {
                    b.Navigation("ViewControllers");
                });

            modelBuilder.Entity("GCatcode.DataBase.Models.CL_Rol", b =>
                {
                    b.Navigation("UserRoles");

                    b.Navigation("ViewRols");
                });

            modelBuilder.Entity("GCatcode.DataBase.Models.CL_View", b =>
                {
                    b.Navigation("ViewControllers");

                    b.Navigation("ViewRols");
                });

            modelBuilder.Entity("GCatcode.DataBase.Models.TR_User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
